import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import fs from "fs";
import path from "path";
import { PdfStrategy } from "../output/pdf-strategy.js";

// Mock downloader
vi.mock("../worker/downloader.js", () => {
  return {
    downloadImage: vi.fn(),
  };
});

// Mock db queries
vi.mock("../db/queries.js", () => {
  return {
    markDone: vi.fn().mockResolvedValue(undefined),
  };
});

import { downloadImage } from "../worker/downloader.js";
import { markDone } from "../db/queries.js";

const mockDownloadImage = vi.mocked(downloadImage);

describe("PdfStrategy Integration", () => {
  let strategy: PdfStrategy;

  beforeEach(() => {
    vi.clearAllMocks();
    
    // Mock downloadImage to return a valid 1x1 PNG buffer
    const oneByOnePng = Buffer.from(
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=",
      "base64"
    );
    mockDownloadImage.mockResolvedValue(oneByOnePng);
    strategy = new PdfStrategy();
  });

  afterEach(() => {
    // Delete only the specific file generated by this test strategy instance
    if (strategy && (strategy as any).pdfPath) {
      const filePath = (strategy as any).pdfPath;
      if (fs.existsSync(filePath)) {
        try {
          fs.unlinkSync(filePath);
        } catch {
          // Ignore if file cannot be deleted
        }
      }
    }
  });

  it("should successfully generate a PDF document from structured blocks", async () => {
    await strategy.init();

    await strategy.save(1, "https://react.dev/docs", {
      title: "React Documentation",
      description: "Learn React library",
      canonicalUrl: "https://react.dev/docs",
      headings: { h1: ["React"], h2: [], h3: [] },
      textContent: "Learn React details...",
      blocks: [
        { type: "heading", level: 1, text: "React Basics" },
        { type: "paragraph", text: "React is a JavaScript library for building user interfaces." },
        { type: "list", items: ["Component-Based", "Declarative UI", "Learn Once, Write Anywhere"] },
        { type: "image", src: "https://react.dev/logo.png", alt: "React Logo" },
      ],
      images: [
        { src: "https://react.dev/logo.png", alt: "React Logo" },
      ],
    });

    await strategy.finish();

    // Verify markDone was called
    expect(markDone).toHaveBeenCalledTimes(1);

    // Verify PDF file was written to the output folder
    const pdfPath = (strategy as any).pdfPath;
    expect(pdfPath).toBeDefined();
    expect(fs.existsSync(pdfPath)).toBe(true);
  });
});
